Biter improvements
OnionGalaxy/TwinlightSouls pull request #119
Opened 2020-08-06 15:21 UTC by Pacasasgar

This PR contains the following features/changes:

-Biter explodes when while dying. This explosion is 'faster' than the normal explosion and players should move away faster.

-Biter height modified - offset has been reduced.

-Bugfix: Biter crashed when players were dead.

-Bugfix: Biter explosion dealt damage only once. The rest of the explosions weren't dealing damage at all.

-Bugfix: Biter explosion cooldown wasn't working correctly and it was difficult for the Biter to explode. Now it has 10 seconds cooldown (need balancing) and will explode always at melee range. Charge cooldown also modified.

2020-09-07 20:29 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +}
this is called Explosion but this just update the position so, I don't understand this method

2020-09-07 20:41 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +	if (next_position.Equals(float3(0, 0, 0)) || App->time->time > time_count_delay)
instead float3(0,0,0) use float3::zero;

2020-09-07 20:43 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +void Biter::ComputeHorizontalVelocity(float3 direction, float speed)
make const float3 direction

2020-09-07 20:45 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +}
this method is called BiteAttack but just move the Bitter, so.... check if it's used if not remove it or change the name and if used and change the name make it const

2020-09-07 20:47 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +	movement = movement.Cross(float3(0, 1, 0));
instead of float3(0,1,0)) use float3::unitY

2020-09-07 20:48 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +	//ComputeVerticalVelocity for charge -> posible TO-DO
remove if not used

2020-09-07 20:50 UTC, JorxSS commented on Scripts/src/Script/Biter.cpp
> +	if (distance <= explosion_radius && abs(current_position.y - target.y) < 10.0F && explosion_current_cooldown <= 0)
10.f is a magic number? make it as a member of the class

2020-09-07 20:52 UTC, JorxSS requested changes
Check the comments and do the changes, it's quite good btw!!

2020-09-08 15:16 UTC, Dartemiss approved these changes
Seems correct! GJ

2020-09-08 16:30 UTC, Pacasasgar commented
> Check the comments and do the changes, it's quite good btw!!

Done!

2020-09-08 17:58 UTC, JorxSS approved these changes
GJ

2020-09-10 01:10 UTC, merged