Feature/clean dependencies
OnionGalaxy/TwinlightSouls pull request #127
Opened 2020-09-07 17:56 UTC by JorxSS

What's new:

* Fixed again Playground
* Cleaning Environment VFX dependencies.
* Fixed water zone damage again, thanks @Dartemiss.

2020-09-07 21:54 UTC, Dartemiss commented on Scripts/src/Script/EventManager.cpp
> +	for (auto & root : root_obstacles)
CS

2020-09-07 22:04 UTC, Dartemiss requested changes
GJ! Works more or less everything but! It crashes when finishing the game on level1 entering the cave (see image below)

EventManager
![imagen](https://user-images.githubusercontent.com/18176345/92418220-abd45900-f166-11ea-9ce6-07930cc8db41.png)

Also you already know but particles takes too much time to spawn.

2020-09-07 22:30 UTC, JorxSS commented on Scripts/src/Script/EventManager.cpp
> +	for (auto & root : root_obstacles)
Done

2020-09-07 22:30 UTC, JorxSS commented
@Dartemiss already fixed the feature/bug now cannot happen sorry mi pana

2020-09-08 09:35 UTC, Dartemiss approved these changes

2020-09-08 14:42 UTC, Pacasasgar commented
I found this bug while testing this version:
![water_death_bug](https://user-images.githubusercontent.com/15977683/92491000-f6e77e00-f1f1-11ea-9907-26f6b0f38e01.gif)

As you mention in the description, water zone has been fixed. Is this another unkown bug? Player do not die but can not move either in the gif's state.

2020-09-08 14:48 UTC, JorxSS commented
> I found this bug while testing this version:
> ![water_death_bug](https://user-images.githubusercontent.com/15977683/92491000-f6e77e00-f1f1-11ea-9907-26f6b0f38e01.gif)
> 
> As you mention in the description, water zone has been fixed. Is this another unkown bug? Player do not die but can not move either in the gif's state.

known, will be fixed with the new animations

2020-09-08 14:49 UTC, Pacasasgar commented
> > I found this bug while testing this version:
> > ![water_death_bug](https://user-images.githubusercontent.com/15977683/92491000-f6e77e00-f1f1-11ea-9907-26f6b0f38e01.gif)
> > As you mention in the description, water zone has been fixed. Is this another unkown bug? Player do not die but can not move either in the gif's state.
> 
> known, will be fixed with the new animations

Great then!

2020-09-08 14:54 UTC, Pacasasgar approved these changes
Nice job Jordi!

2020-09-08 15:05 UTC, merged