feature/acceleration_and_deceleration
OnionGalaxy/TwinlightSouls pull request #160
Opened 2020-09-27 13:03 UTC by raulgonzalezupc

- Acceleartion of the player when starts moving
- Deceleration of the player when stops moving
- Inspector on the variables

2020-09-27 19:26 UTC, marcorod94 reviewed
Looks nice great job

2020-09-27 19:26 UTC, marcorod94 commented on Scripts/src/Script/PlayerMovement.cpp
> +{
Codestyle

2020-09-27 19:38 UTC, marcorod94 approved these changes
Nice job

2020-09-27 20:37 UTC, raulgonzalezupc commented on Scripts/src/Script/PlayerMovement.cpp
> +{
didn't notice, sorry, fixed!

2020-09-28 09:30 UTC, Dartemiss requested changes
The feeling for me is very weird is like skating on ice, especially when you change direction or you spin.
I would apply acceleration only the first time you are putting input, and if u change the input (turn or spin velocity) don't apply it.

2020-10-01 16:03 UTC, Dartemiss commented on Scripts/src/Script/PlayerMovement.h
> +	float deceleration = 0.035F;
f lowercase for code style

2020-10-03 13:56 UTC, mariofv reviewed
I tried it, and I have the feeling that the player is sliding when turning :S

2020-10-04 10:35 UTC, raulgonzalezupc commented
> I tried it, and I have the feeling that the player is sliding when turning :S
This is probably because you are turning when you haven't reach yet the top velocity and is still doing the acceleration. I'm going to change it to make it smooth

2020-10-04 10:45 UTC, raulgonzalezupc commented
> I tried it, and I have the feeling that the player is sliding when turning :S

This is probably because you are turning when you haven't reach yet the top velocity and is still doing the acceleration. I'm going to change it to make it smooth

2020-10-08 16:33 UTC, Dartemiss approved these changes
LGTM

2020-10-10 20:52 UTC, merged