Feature/skip cinematics
OnionGalaxy/TwinlightSouls pull request #171
Opened 2020-10-01 21:20 UTC by marcorod94

Skip cinematics using punch button J\B

Known hiccup the skip UI may not appear on the first run sometimes

2020-10-02 12:41 UTC, Dartemiss commented on Scripts/src/Script/CinematicCamera.cpp
> +		if (input_manager->GetGameInputDown("Punch", static_cast<PlayerID>(player_1->player_controller->player - 1)))
Only player1 can skil cinematics?

2020-10-02 12:41 UTC, Dartemiss commented on Scripts/src/Script/UIManager.cpp
> +}
const

2020-10-02 12:42 UTC, Dartemiss commented on Scripts/src/Script/UIManager.cpp
> +}
const

2020-10-02 12:42 UTC, Dartemiss requested changes
Works fine but I haven't seen any UI at all, even restarting. Also some const correctness

2020-10-08 06:43 UTC, marcorod94 commented on Scripts/src/Script/CinematicCamera.cpp
> +		if (input_manager->GetGameInputDown("Punch", static_cast<PlayerID>(player_1->player_controller->player - 1)))
Yes only the player1 could do that

2020-10-13 07:58 UTC, yalania reviewed
I tried it but it doesn't work for me, the skip ui stay on the middle of the screen (I tried J in keyboard and B in controller)

2020-10-14 16:49 UTC, yalania approved these changes
now it works fine

2020-10-14 16:53 UTC, yalania requested changes
I tried second cinematic, and when you skip it continues playing at the moment it was skip.

2020-10-14 22:43 UTC, marcorod94 commented
Everything done please check it

2020-11-04 19:46 UTC, Dartemiss commented
This uses old cinematic system so I close this.

2020-11-04 19:46 UTC, closed without merging