Feature/fix roots
OnionGalaxy/TwinlightSouls pull request #172
Opened 2020-10-02 15:04 UTC by RickyVimon

What's new?

- New logic for the roots. Now the roots vector is aligned with the Zones vector; So, roots_obstacles[3] will return the root Game Object on the Zone 3. Will return nullptr if there are no roots on that area. Nullptr checks have been set to control any crash.
- InitRoots is done together with the InitZones.
- Ingame now if the player respwans on a checkpoint, all the roots which have been passed will be down.
- Earthquake sound fixed with respawning.

2020-10-02 17:18 UTC, Dartemiss commented on Scripts/src/Script/EventManager.h
> +	//std::vector<GameObject*> root_zones;
why is comented?

2020-10-03 12:38 UTC, Dartemiss requested changes
Work fine except the sound, If you finish zone 3 of level1 and purify everything the sound becomes purified when respawning.

2020-10-07 17:29 UTC, RickyVimon commented on Scripts/src/Script/EventManager.h
> +	//std::vector<GameObject*> root_zones;
solved

2020-10-08 03:33 UTC, Pacasasgar requested changes
I tested your branch:

1. Roots don't reproduce sound when you purify them, at least after beating battle zone 1, so first roots (I can't hear the 'earthquake' sound).

2. If I die in the River and re-spawn after battle zone 2, roots are there again behind me.

PD: Which scene should I be using to test? Level1.scene or Level1_roots.scene? I tried both of them and above issues still happened so maybe I'm just missing something.

2020-10-08 08:22 UTC, RickyVimon commented
> I tested your branch:
> 
> 1. Roots don't reproduce sound when you purify them, at least after beating battle zone 1, so first roots (I can't hear the 'earthquake' sound).
> 2. If I die in the River and re-spawn after battle zone 2, roots are there again behind me.
> 
> PD: Which scene should I be using to test? Level1.scene or Level1_roots.scene? I tried both of them and above issues still happened so maybe I'm just missing something.

I have just tested it and it works on my branch. Are you sure you are up to date to develop in the engine and on the feature/fix_roots branch?

2020-10-08 12:23 UTC, Pacasasgar commented
> > I tested your branch:
> > 
> > 1. Roots don't reproduce sound when you purify them, at least after beating battle zone 1, so first roots (I can't hear the 'earthquake' sound).
> > 2. If I die in the River and re-spawn after battle zone 2, roots are there again behind me.
> > 
> > PD: Which scene should I be using to test? Level1.scene or Level1_roots.scene? I tried both of them and above issues still happened so maybe I'm just missing something.
> 
> I have just tested it and it works on my branch. Are you sure you are up to date to develop in the engine and on the feature/fix_roots branch?

As discussed on discord, I will approve now the PR. Regarding my problems:

1. It is not an issue caused by thir PR changes. It's a new bug probably caused by the implementation of the new XML parser in the soundbank events. This will be fixed in another branch.

2. It was working fine if you play normally the game. The problem I described appears when using 'F1' cheat mode to teleport to different zones. You appear behind the roots.

2020-10-08 12:23 UTC, Pacasasgar approved these changes

2020-10-08 16:09 UTC, Dartemiss approved these changes
LGTM

2020-10-08 16:09 UTC, merged