Feature/powerups
OnionGalaxy/TwinlightSouls pull request #176
Opened 2020-10-08 17:02 UTC by JordiRomagosa

Changes made:

- Unified the enemy drops into a single class for light orbs (healing) and powerups.
- Implemented two powerups: increased attack and invulnerability.
- Powerups have a greater chance to drop as more enemies are killed, but the chances are never 0% nor 100%.
- Added little feedback (vfx) for the players to know they have the powerup active.

Still waiting for the UI feedback that is not implemented yet.

2020-10-14 12:08 UTC, Dartemiss commented on Scripts/src/Script/LightOrb.cpp
>  void LightOrb::Update()
Why is LightOrb class needed now?

2020-10-14 12:09 UTC, Dartemiss commented on Scripts/src/Script/LightOrb.h
> +	//void Start() override;
If not used delete it

2020-10-14 12:11 UTC, Dartemiss commented on Scripts/src/Script/PlayerController.cpp
> +	float delta_time = App->time->delta_time / 1000;
1000.f

2020-10-14 12:11 UTC, Dartemiss commented on Scripts/src/Script/PlayerController.cpp
> +	if (time_remaining_attack_powerup != 0)
.f

2020-10-14 12:12 UTC, Dartemiss commented on Scripts/src/Script/PowerUp.cpp
> +	}
Probably is more readable to have all of this on a separate method

2020-10-14 12:14 UTC, Dartemiss commented on Scripts/src/Script/PowerUp.cpp
> +		player_to_deliver_controller->time_remaining_invulnerable_powerup += invulnerable_powerup_duration;
This means that if a player gets 3 powerups at the same time he will have the bonus the triple of the time right?

2020-10-14 12:15 UTC, Dartemiss commented on Scripts/src/Script/PowerUp.cpp
> +void PowerUp::PickupActivatePowerup()
This method can be const

2020-10-14 12:16 UTC, Dartemiss commented on Scripts/src/Script/PowerUp.cpp
> +void PowerUp::SetupPowerupVfx()
Can be cosnt aswell

2020-10-14 12:29 UTC, Dartemiss requested changes
GJ man!
I tested the branch and some things:
- The branch is very deprecated you have to merge develop here
- The level1/level2/boss scenes crashes because you just used level1_powerpus.scene for testing, please delete this scene from production
- I think the drops should have a lot more range to get collected like the current lightorbs otherwise is very tedious to get all of them (attracting_radio  should be bigger)
- The damage bonus is good but the invulnerable bonus doesn't have any feedback (or at least i couldn't see anything so I looked like a bug not receiving damage)
- The light ball doesn't have bonus damage?

2020-10-14 18:13 UTC, JordiRomagosa commented on Scripts/src/Script/PowerUp.cpp
> +		player_to_deliver_controller->time_remaining_invulnerable_powerup += invulnerable_powerup_duration;
Yes, it is. In fact is very hard due to the drop rate, but for now I made it like this. To change it to "refresh duration" is as simple as changing the += for a =.

2020-10-19 16:08 UTC, JordiRomagosa commented
Realized requested changes and updated to develop.

2020-10-20 13:54 UTC, Dartemiss approved these changes
Okay looks good now!
Prepare some prefabs of the changes in the scenes. After we merge the big branches with the new level1/level2 and boss we'll merge this branch first after those.

As general comments I think that the red powerup is too long but is just my opinion and can be discussed for next delivery. 
GJ

2020-10-21 11:28 UTC, merged