Fix/7_tutorial_skippable
OnionGalaxy/TwinlightSouls pull request #178
Opened 2020-10-11 12:42 UTC by raulgonzalezupc

What's new?
- Now you can skip the tutorial and conversations of the ally on level 1
- Fix bug that you can cast the shield on a conversation
- When teleported you get the lightball

2020-10-11 16:35 UTC, yalania commented
- I think the control are the other side, it said press 'Z' for skipping but you have to press 'X' 
- We need final art for this. and probably some buttons with a cursor instead of a press Z or X
- If you skip the tutorial the ally is not teleported to the second  zone so the placeholder mesh is shown, you may can remove the mesh component or disable it.
- I can't pass from first zone.
- You already got the lightball when teleported what is need on that part?

2020-10-11 16:39 UTC, yalania commented on Scripts/src/Script/AllyTrigger.cpp
> +		SetPlayersPositions(player_1_inside, player_2_inside);
In this case you I think you can skip the SetPlayersPositions

2020-10-11 16:40 UTC, yalania commented on Scripts/src/Script/DialogueManager.cpp
> +	int i = 0;
you can remove this.

2020-10-11 16:41 UTC, yalania requested changes
There are some needed changes to do, but good job :D

2020-10-11 16:41 UTC, yalania commented on Scripts/src/Script/AllyInteractionsScript.h
> +	TutorialHelper* GetTutorialHelper();
use const for getter methods in general

2020-10-11 20:35 UTC, Dartemiss commented on Scripts/src/Script/AllyInteractionsScript.cpp
> +}
Const on all getters

2020-10-11 20:36 UTC, Dartemiss commented on Scripts/src/Script/AllyTrigger.cpp
> +				// player wants to do the tutorial or not, if the player doesn't want the tutorial, put complains to false, if he wants, then everything remains the same.
Is this TODO done?

2020-10-11 20:42 UTC, Dartemiss commented on Scripts/src/Script/AllyTrigger.h
> +	inline void SetComplain(bool complain) {this->complains = complain; };
put this on cpp

2020-10-11 20:44 UTC, Dartemiss commented on Scripts/src/Script/AllyTrigger.cpp
> +	if (input_manager->GetKeyDown(KeyCode::Z))
This is too harcoded, u should use a GameInput for being able to do it with gamecontroller

2020-10-11 20:53 UTC, Dartemiss requested changes
GJ! But there are several things that doesn't work.
- As anabel said, we should put final art as soon as possible and on game you don't know which buttons you have to press for skipping tutorial
- Also as I commented on code, the skip buttons should be GameInputs allowing players with controllers to skip the tutorial
- As anabel commented aswell, when you skip the tutorial the ally keeps on the tree and is quite contradictory if he becomes the lightball and also a white spheere mesh is visible on the second position of the ally. My suggestion would be disable that mesh and maybe give the lightball at the moment that you skip the tutorial and make the ally disapear aswell.
- Lastly, on this branch the game is bugged on battle zone1 and only the first wave spawns, making a game crashing bug and player cannot pass that part .

2020-10-14 16:48 UTC, yalania commented
Now when I press the buttons nothing happens. And I already did the get lightball when teleporting, so it weird it was not working, can you point me to the place were you fixed it on the code?

2020-10-14 17:05 UTC, yalania approved these changes
Ok, needed to get latest develop in engine, my bad

2020-10-16 09:41 UTC, raulgonzalezupc commented
> Now when I press the buttons nothing happens. And I already did the get lightball when teleporting, so it weird it was not working, can you point me to the place were you fixed it on the code?

tbh, i didn't know that you did that, I just thought since I gave the lightball to the player when enter the zone 1, why not give it to him when teleporting, so I did haha

2020-10-16 15:13 UTC, closed without merging