Feature/shield update
OnionGalaxy/TwinlightSouls pull request #199
Opened 2020-10-19 13:51 UTC by vidalmelero

Implemented feature:

Now the shield bar is attatched to the player. 

Only visible when the player uses the shield.

2020-10-19 19:31 UTC, Dartemiss commented on Scripts/src/Script/ShieldBar.cpp
> +void ShieldBar::SetPlayerPosition(float3 position)
const reference

2020-10-19 19:32 UTC, Dartemiss commented on Scripts/src/Script/UIManager.cpp
> +
const

2020-10-19 19:40 UTC, Dartemiss requested changes
You have to merge develop on this branch.
Also when shield is broken when you press the button nothing has to be shown.
https://gyazo.com/1d467437f6d9aacff1de7066c8687da0

2020-10-20 15:40 UTC, raulgonzalezupc commented on Scripts/src/Script/ShieldBar.cpp
> +void ShieldBar::SetPlayerPosition(const float3 position)
void ShieldBar::SetPlayerPosition(const float3& position)

2020-10-20 15:43 UTC, raulgonzalezupc commented on Scripts/src/Script/ShieldBar.cpp
> +
with default not need for that

2020-10-20 15:44 UTC, raulgonzalezupc commented on Scripts/src/Script/ShieldBar.cpp
> +void ShieldBar::SetShieldStatus()
this can be const

2020-10-20 15:51 UTC, raulgonzalezupc commented on Scripts/src/Script/UIManager.h
>  class UILives;
line 31 and 32 can be deleted since its comented

2020-10-20 16:28 UTC, vidalmelero commented on Scripts/src/Script/UIManager.h
>  class UILives;
I didn't do that, maybe someone wants to keep that comented

2020-10-20 16:47 UTC, raulgonzalezupc commented
![image](https://user-images.githubusercontent.com/56253770/96618061-ba389780-1304-11eb-959f-1f24012ebf18.png)

2020-10-20 17:43 UTC, raulgonzalezupc commented
Also, when the shield is breaked, I would suggest to put something on the screen to show the player that he can't use the shield even if he does not press the button. Like showing the bar refilling but again, smaller

2020-10-20 19:31 UTC, vidalmelero commented
Okey, now the shield bar is showed too when the shield is recovering, and i set the size a little bit lower.

2020-10-23 16:16 UTC, Dartemiss commented
Merge it again with develop for aproval

2020-11-04 19:45 UTC, Dartemiss commented
As you created another PR I close this one.

2020-11-04 19:45 UTC, closed without merging